name: Systemli - Your friendly tech collective
pygments: true
source: ./src
paginate: 5
paginate_path: "/news/page-:num"
include: [.well-known,.htaccess]

paginate_per_category: true
default_category: "de"
